export const ADD_VISITORS = "ADD_VISITORS";
export const ADD_UNREAD_TICKETS = "ADD_UNREAD_TICKETS";
export const ADD_UNREAD_CHATS = "ADD_UNREAD_CHATS";
export const ADD_UPCOMING_BOOKINGS = "ADD_UPCOMING_BOOKINGS";
